# Generated by Django 3.2.4 on 2021-08-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_alter_saleoffer_exp_date'),
        ('accounts', '0003_rename_membership_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartMembership',
        ),
    ]
