# Generated by Django 3.2.4 on 2021-08-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210823_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'In progress'), ('S', 'Sent'), ('D', 'Delivered')], default='P', max_length=1),
        ),
    ]
