# Generated by Django 3.2.4 on 2021-08-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
                ('weight', models.PositiveIntegerField(help_text='Please pass the weight in grams.')),
                ('height', models.PositiveIntegerField(help_text='Please pass the weight in centimeters.')),
                ('length', models.PositiveIntegerField(help_text='Please pass the weight in centimeters.')),
                ('width', models.PositiveIntegerField(help_text='Please pass the weight in centimeters.')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('HG', 'House and Garden'), ('EL', 'Electronics'), ('FA', 'Fashion'), ('AM', 'Automotive'), ('SP', 'Sport'), ('BE', 'Beauty'), ('HE', 'Health'), ('OT', 'Other')], default='OT', max_length=2)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
