# Generated by Django 3.2.4 on 2021-08-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_saleoffer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product_name',
            new_name='name',
        ),
    ]
