# Generated by Django 3.2.4 on 2021-08-06 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20210806_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 5, 18, 15, 56, 30900, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='title',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
