# Generated by Django 3.2.4 on 2021-08-11 16:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0010_auto_20210806_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleoffer',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 16, 52, 13, 133510, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='first_image',
            field=models.ImageField(default='default.jpg', help_text='This image will be shown in search results.', upload_to='items'),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='second_image',
            field=models.ImageField(default='default.jpg', help_text='Secondary image.', upload_to='items'),
        ),
    ]
