# Generated by Django 3.2.4 on 2021-08-11 16:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0011_auto_20210811_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleoffer',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 16, 54, 18, 600939, tzinfo=utc), editable=False),
        ),
    ]
