# Generated by Django 3.2.4 on 2021-08-12 11:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20210811_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 11, 18, 4, 683937, tzinfo=utc), editable=False),
        ),
    ]
