# Generated by Django 3.2.4 on 2021-08-16 07:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0015_alter_saleoffer_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleoffer',
            name='dealer',
        ),
        migrations.AddField(
            model_name='item',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 15, 7, 55, 46, 424883, tzinfo=utc), editable=False),
        ),
    ]
