# Generated by Django 3.2.4 on 2021-08-18 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_saleoffer_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 11, 7, 31, 40674, tzinfo=utc), editable=False),
        ),
    ]
