# Generated by Django 3.2.4 on 2021-08-22 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_alter_saleoffer_exp_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='saleoffer',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 20, 13, 52, 790915, tzinfo=utc), editable=False),
        ),
    ]
