# Generated by Django 3.2.4 on 2021-08-22 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_auto_20210822_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 20, 19, 22, 237367, tzinfo=utc), editable=False),
        ),
    ]
