# Generated by Django 3.2.4 on 2021-08-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_alter_saleoffer_exp_date'),
        ('accounts', '0006_order_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.saleoffer'),
        ),
    ]
