# Generated by Django 3.2.4 on 2021-08-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Sent', 'Sent'), ('Delivered', 'Delivered')], default='In progress', max_length=20),
        ),
    ]
