# Generated by Django 3.2.4 on 2021-08-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmembership',
            old_name='item',
            new_name='cart_item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='order_items',
        ),
        migrations.RenameField(
            model_name='ordermembership',
            old_name='item',
            new_name='order_item',
        ),
    ]
