# Generated by Django 3.2.4 on 2021-08-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210824_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmembership',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordermembership',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
