# Generated by Django 3.2.4 on 2021-08-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_notification_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
        migrations.AddField(
            model_name='notification',
            name='sale_info',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='shipping_info',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
