# Generated by Django 3.2.4 on 2021-08-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210826_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
