# Generated by Django 3.2.4 on 2021-08-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_notification_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('order', 'Order'), ('shipping', 'Shipping')], default='order', max_length=20),
        ),
    ]
