# Generated by Django 3.2.4 on 2021-08-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210828_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='sale',
        ),
    ]
