# Generated by Django 3.2.4 on 2021-08-06 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_saleoffer_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleoffer',
            name='first_image',
            field=models.ImageField(default='default.jpg', help_text='This image will be shown in search results.', upload_to='offer_pictures'),
        ),
        migrations.AddField(
            model_name='saleoffer',
            name='second_image',
            field=models.ImageField(default='default.jpg', help_text='Secondary image.', upload_to='offer_pictures'),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 5, 17, 25, 21, 83198, tzinfo=utc), editable=False),
        ),
    ]
