# Generated by Django 3.2.4 on 2021-08-16 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20210816_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 15, 7, 53, 44, 495829, tzinfo=utc), editable=False),
        ),
    ]
