# Generated by Django 3.2.4 on 2021-08-24 13:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0027_alter_saleoffer_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Please pass the quantity of this item that you have to sell.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.PositiveIntegerField(help_text='Please pass the height in meters.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.PositiveIntegerField(help_text='Please pass the length in meters.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.PositiveIntegerField(help_text='Please pass the weight in kilograms.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.PositiveIntegerField(help_text='Please pass the width in meters.'),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 13, 44, 37, 68092, tzinfo=utc), editable=False),
        ),
    ]
