# Generated by Django 3.2.4 on 2021-08-24 14:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_auto_20210824_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 14, 28, 36, 802354, tzinfo=utc), editable=False),
        ),
    ]
