# Generated by Django 3.2.4 on 2021-08-24 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0029_alter_saleoffer_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Please pass the height in meters.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.PositiveIntegerField(blank=True, help_text='Please pass the length in meters.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Please pass the weight in kilograms.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Please pass the width in meters.'),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 15, 59, 37, 135447, tzinfo=utc), editable=False),
        ),
    ]
