# Generated by Django 3.2.4 on 2021-08-25 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0032_auto_20210824_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 14, 52, 5, 9649, tzinfo=utc), editable=False),
        ),
    ]
