# Generated by Django 3.2.4 on 2021-08-26 20:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0036_alter_saleoffer_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 20, 57, 41, 791968, tzinfo=utc), editable=False),
        ),
    ]
