# Generated by Django 3.2.4 on 2021-08-31 23:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0045_alter_saleoffer_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleoffer',
            name='first_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleoffer',
            name='second_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleoffer',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 23, 13, 7, 701503, tzinfo=utc), editable=False),
        ),
    ]
